export const endpoints = {
  auth: {
    login: '/auth/login',
    callback: '/auth/callback',
    refresh: '/auth/refresh',
    me: '/auth/me',
  },
  transactions: {
    list: '/transactions',
    detail: (id: string) => `/transactions/${id}`,
    import: '/transactions/import',
    export: '/transactions/export',
    categorize: (id: string) => `/transactions/${id}/categorize`,
    batchCategorize: '/transactions/categorize/batch',
    suggestions: (id: string) => `/transactions/${id}/suggestions`,
    split: (id: string) => `/transactions/${id}/splits`,
  },
  invoices: {
    list: '/invoices',
    detail: (id: string) => `/invoices/${id}`,
    generate: '/invoices/generate',
    send: '/invoices/send',
    pdf: (id: string) => `/invoices/${id}/pdf`,
  },
  payments: {
    list: '/payments',
    detail: (id: string) => `/payments/${id}`,
    match: '/payments/match',
    allocate: (id: string) => `/payments/${id}/allocate`,
    suggestions: (id: string) => `/payments/${id}/suggestions`,
  },
  arrears: {
    // Arrears is served under /payments/arrears
    list: '/payments/arrears',
    summary: '/payments/arrears',
    sendReminder: '/arrears/reminder',
  },
  parents: {
    list: '/parents',
    detail: (id: string) => `/parents/${id}`,
    children: (id: string) => `/parents/${id}/children`,
    sendOnboardingInvite: (id: string) => `/parents/${id}/send-onboarding-invite`,
  },
  children: {
    list: '/children',
    detail: (id: string) => `/children/${id}`,
    enroll: '/children/enroll',
  },
  sars: {
    vat201: '/sars/vat201',
    emp201: '/sars/emp201',
    submit: (id: string) => `/sars/${id}/submit`,
    submissions: '/sars/submissions',
  },
  reconciliation: {
    list: '/reconciliation',
    reconcile: '/reconciliation',
    summary: '/reconciliation/summary',
    incomeStatement: '/reconciliation/income-statement',
    discrepancies: '/reconciliation/discrepancies',
  },
  staff: {
    list: '/staff',
    detail: (id: string) => `/staff/${id}`,
  },
  payroll: {
    list: '/payroll',
    detail: (id: string) => `/payroll/${id}`,
    process: '/payroll/process',
  },
  dashboard: {
    metrics: '/dashboard/metrics',
    trends: '/dashboard/trends',
    learningMode: '/dashboard/learning-mode',
    availablePeriods: '/dashboard/available-periods',
  },
  feeStructures: {
    list: '/fee-structures',
    detail: (id: string) => `/fee-structures/${id}`,
  },
  adhocCharges: {
    list: (invoiceId: string) => `/invoices/${invoiceId}/charges`,
    add: (invoiceId: string) => `/invoices/${invoiceId}/charges`,
    remove: (invoiceId: string, lineId: string) => `/invoices/${invoiceId}/charges/${lineId}`,
  },
  users: {
    tenantUsers: (tenantId: string) => `/tenants/${tenantId}/users`,
    updateRole: (tenantId: string, userId: string) => `/tenants/${tenantId}/users/${userId}/role`,
    removeUser: (tenantId: string, userId: string) => `/tenants/${tenantId}/users/${userId}`,
    invite: (tenantId: string) => `/tenants/${tenantId}/invitations`,
    invitations: (tenantId: string) => `/tenants/${tenantId}/invitations`,
    resendInvitation: (tenantId: string, invitationId: string) => `/tenants/${tenantId}/invitations/${invitationId}/resend`,
    revokeInvitation: (tenantId: string, invitationId: string) => `/tenants/${tenantId}/invitations/${invitationId}`,
  },
  tenants: {
    me: '/tenants/me',
    detail: (id: string) => `/tenants/${id}`,
    update: (id: string) => `/tenants/${id}`,
  },
  xero: {
    status: '/xero/status',
    sync: '/xero/sync',
    connect: '/xero/connect',
    disconnect: '/xero/disconnect',
    bankAccounts: '/xero/bank-accounts',
    bankConnections: '/xero/bank-connections',
    connectBankAccount: '/xero/bank-accounts/connect',
    disconnectBankAccount: '/xero/bank-accounts/disconnect',
    accounts: '/xero/accounts',
    syncAccounts: '/xero/sync-accounts',
  },
  statements: {
    list: '/statements',
    detail: (id: string) => `/statements/${id}`,
    pdf: (id: string) => `/statements/${id}/pdf`,
    generate: '/statements/generate',
    generateBulk: '/statements/generate/bulk',
    finalize: (id: string) => `/statements/${id}/finalize`,
    deliver: (id: string) => `/statements/${id}/deliver`,
    forParent: (parentId: string) => `/statements/parents/${parentId}`,
    parentAccount: (parentId: string) => `/statements/parents/${parentId}/account`,
  },
  xeroSplits: {
    detect: '/reconciliation/xero-splits/detect',
    create: '/reconciliation/xero-splits',
    list: '/reconciliation/xero-splits',
    summary: '/reconciliation/xero-splits/summary',
    detail: (id: string) => `/reconciliation/xero-splits/${id}`,
    confirm: (id: string) => `/reconciliation/xero-splits/${id}/confirm`,
    cancel: (id: string) => `/reconciliation/xero-splits/${id}/cancel`,
    byXeroTransaction: (xeroTxnId: string) => `/reconciliation/xero-splits/by-xero-transaction/${xeroTxnId}`,
  },
  communications: {
    broadcasts: '/communications/broadcasts',
    broadcastDetail: (id: string) => `/communications/broadcasts/${id}`,
    sendBroadcast: (id: string) => `/communications/broadcasts/${id}/send`,
    cancelBroadcast: (id: string) => `/communications/broadcasts/${id}/cancel`,
    previewRecipients: '/communications/recipients/preview',
    groups: '/communications/groups',
    groupDetail: (id: string) => `/communications/groups/${id}`,
  },
  admin: {
    contactSubmissions: '/admin/contact-submissions',
    demoRequests: '/admin/demo-requests',
    updateContactSubmissionStatus: (id: string) => `/admin/contact-submissions/${id}/status`,
    updateDemoRequestStatus: (id: string) => `/admin/demo-requests/${id}/status`,
  },
  apiKeys: {
    list: '/auth/api-keys',
    create: '/auth/api-keys',
    detail: (id: string) => `/auth/api-keys/${id}`,
    revoke: (id: string) => `/auth/api-keys/${id}`,
    rotate: (id: string) => `/auth/api-keys/${id}/rotate`,
  },
} as const;
