#!/bin/bash
# Generate all required cryptographic secrets for CrecheBooks
# Usage: ./scripts/generate-secrets.sh

set -e

echo "🔐 CrecheBooks Secrets Generator"
echo "================================="
echo ""
echo "Generating cryptographically secure secrets..."
echo ""

echo "📋 Copy these secrets to your environment:"
echo ""
echo "# ============================================"
echo "# Critical Secrets (REQUIRED)"
echo "# ============================================"
echo ""
echo "# Encryption key for sensitive data (PII, tokens, credentials)"
echo "ENCRYPTION_KEY=$(openssl rand -base64 32)"
echo ""
echo "# JWT secret for authentication tokens"
echo "JWT_SECRET=$(openssl rand -base64 32)"
echo ""
echo "# NextAuth secret for web app sessions"
echo "NEXTAUTH_SECRET=$(openssl rand -base64 32)"
echo ""
echo "# Xero OAuth state encryption key"
echo "XERO_STATE_KEY=$(openssl rand -base64 32)"
echo ""
echo "# Token encryption for stored OAuth tokens"
echo "TOKEN_ENCRYPTION_KEY=$(openssl rand -base64 32)"
echo ""
echo "# ============================================"
echo "# Optional Webhook Secrets"
echo "# ============================================"
echo ""
echo "# Mailgun webhook signing key (get from Mailgun dashboard)"
echo "# MAILGUN_WEBHOOK_SIGNING_KEY=<from-mailgun-dashboard>"
echo ""
echo "# SendGrid webhook key (get from SendGrid dashboard)"
echo "# SENDGRID_WEBHOOK_KEY=<from-sendgrid-dashboard>"
echo ""
echo "# WhatsApp webhook verify token (create your own)"
echo "WHATSAPP_WEBHOOK_VERIFY_TOKEN=$(openssl rand -hex 32)"
echo ""
echo "# ============================================"
echo ""
echo "✅ Secrets generated successfully!"
echo ""
echo "📝 Next steps:"
echo "   1. Copy these to apps/api/.env for local development"
echo "   2. Set in GitHub: gh secret set <NAME> --repo Smashkat12/crechebooks"
echo "   3. Set in Railway: railway variables set <NAME>=\"<value>\""
echo ""
echo "⚠️  SECURITY WARNING:"
echo "   - Never commit these secrets to Git"
echo "   - Store them securely in a password manager"
echo "   - Use different secrets for dev/staging/production"
echo ""
